
admin_index:
  path:       /admin/index
  controller: App\Controller\Admin\BlogController::index

admin_post_index:
  path:       /admin/index
  controller: App\Controller\Admin\BlogController::index

admin_post_new:
  path:       /admin/post/new
  controller: App\Controller\Admin\BlogController::new

admin_post_edit:
  path:       /admin/{id}/edit
  controller: App\Controller\Admin\BlogController::edit
  requirements:
    page: '\d+'

admin_post_delete:
  path:       /admin/{id}/delete
  controller: App\Controller\Admin\BlogController::delete
  requirements:
    page: '\d+'

admin_post_show:
  path:       /admin/post/{id}
  controller: App\Controller\Admin\BlogController::show
  requirements:
    page: '\d+'