controllers:
    resource: ../src/Controller/
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

redirect:
    path: /
    controller: App\Controller\RedirectController::redirectToLocale

homepage:
    path: /{_locale}
    requirements:
        _locale: '%app_locales%'
    controller: App\Controller\SiteController::homepage
    defaults:
        _locale: '%locale%'

homepage2:
    path: /fr
    requirements:
        _locale: '%app_locales%'
    controller: App\Controller\SiteController::homepage

app_logout:
    path: /logout
    methods: GET

admin:
    resource: 'routes/admin.yaml'
    prefix:   /{_locale}
    requirements:
        _locale: '%app_locales%'
